### register request
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username":"johndoe",
    "email":"johndoe@gmail.com",
    "mobile":"09223332200",
    "password":"1234512345",
    "confirm_password":"1234512345"
}


### login request
POST http://localhost:3000/auth/login
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
    "username":"ali1995ez2",
    "password":"1234512345"
}