### create team
POST http://localhost:3000/team/create
Authorization: Bearer {{$dotenv JWT_TOKEN}}
Content-Type: application/json

{
    "name":"title of new Team",
    "description":"text of new Team for project manager of node js course",
    "username":"ali1 995ez2"
}

### get all teams
GET http://localhost:3000/team/list
Authorization: Bearer {{$dotenv JWT_TOKEN}}
Content-Type: application/json

### get team by id
GET  http://localhost:3000/team/6363591635f88bf29c75035c
Authorization: Bearer {{$dotenv JWT_TOKEN}}
Content-Type: application/json

### get my teams
GET  http://localhost:3000/team/me
Authorization: Bearer {{$dotenv JWT_TOKEN}}
Content-Type: application/json

### delete team by id
DELETE  http://localhost:3000/team/remove/636357daaf72ed357121221c
Authorization: Bearer {{$dotenv JWT_TOKEN}}
Content-Type: application/json

### invite user to team
GET  http://localhost:3000/team/invite/6363591635f88bf29c75035c/johndoe
Authorization: Bearer {{$dotenv JWT_TOKEN}}
Content-Type: application/json
